---
name: Geo-Coordinates-ITM
version: 0.02

author:
  - 'Andy Armstrong <andy@hexten.net>'
abstract: Convert coordinates between lat/lon and Irish Transverse Mercator
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Geo-Coordinates-ITM
  license: http://dev.perl.org/licenses/
  repository: https://svn.hexten.net/andy/Perl/Geo-Coordinates-ITM/trunk
requires:
  Test::More: 0
  Test::Number::Delta: 1.03
provides:
  Geo::Coordinates::ITM:
    file: lib/Geo/Coordinates/ITM.pm
    version: 0.01
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
